version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout      

      - run:
          name: install dependencies
          command: |

            conda install python=3.9.12.final.0

            conda install -c conda-forge parameterized 
            conda install -qy conda-build anaconda-client pytest pytest-cov

            conda install -y pytorch==1.9.0 cudatoolkit=10.2 -c pytorch
            
            conda install -y pyg -c pyg -c conda-forge
            conda install -y -c plotly plotly 

            conda config --set auto_update_conda no
            conda info -a

      - run:
          name: run tests
          command: |
            # source activate adj
            pytest --color=yes -v --cov=HyDGL tests
            conda install -c conda-forge codecov
            codecov -t eacef7a6-3ec3-47f5-b294-9fb90e474591

      - store_artifacts:
          path: test-reports
          destination: test-reports
